FORMATION_DICT = {"_343":{"name" : "3-4-3",
         "formation" : {"ATT":["LW", "ST", "RW"], "MID":["LM", "CM", "RM"], "DEF":["CB"]},
         "formation_priority" : ["ST", "CB", "CM", "LW", "RW", "LM", "RM", "GK"],
         "formation_num" : {"ST":1, "CB":3, "CM":2, "LW":1, "RW":1, "LM":1, "RM":1, "GK":1},
         "formation_shooting_rate" : [2, 4, 2, 1, 1.5, 1.5, 1, 0.5, 0.5, 0.5, 0],
         "formation_assist_rate" : [2, 1.5, 2, 2, 3, 3, 2, 0.5, 0.7, 0.5, 0]},
"_433":{"name" : "4-3-3",
         "formation" : {"ATT":["LW", "ST", "RW"], "MID":["CM", "CDM"], "DEF":["LB", "CB", "RB"]},
         "formation_priority" : ["ST", "CB", "CM", "CDM", "LW", "RW", "LB", "RB", "GK"],
         "formation_num" : {"ST":1, "CB":2, "CM":2, "CDM":1, "LW":1, "RW":1, "LB":1, "RB":1, "GK":1},
         "formation_shooting_rate" : [2, 3, 2, 1.5, 1.5, 1, 1, 0.5, 0.5, 1, 0],
         "formation_assist_rate" : [2, 1.5, 2, 2.5, 2.5, 1, 1.5, 0.5, 0.5, 1.5, 0]},
"_4231":{"name" : "4-2-3-1",
         "formation" : {"ATT":["ST"], "MID":["LM", "RM", "CAM", "CDM"], "DEF":["LB", "CB", "RB"]},
         "formation_priority" : ["ST", "CB", "CAM", "CDM", "LM", "RM", "LB", "RB", "GK"],
         "formation_num" : {"ST":1, "CB":2, "CAM":1, "CDM":2, "LM":1, "RM":1, "LB":1, "RB":1, "GK":1},
         "formation_shooting_rate" : [4, 2, 3, 2, 1, 1, 1, 0.5, 0.5, 0.5, 0],
         "formation_assist_rate" : [2, 2, 3, 2, 1.5, 1.5, 1.5, 0.5, 0.5, 1.5, 0]},
"_442":{"name" : "4-4-2",
         "formation" : {"ATT":["ST"], "MID":["LM", "RM", "CM"], "DEF":["LB", "CB", "RB"]},
         "formation_priority" : ["ST", "CB", "CM", "LM", "RM", "LB", "RB", "GK"],
         "formation_num" : {"ST":2, "CB":2, "CM":2, "LM":1, "RM":1, "LB":1, "RB":1, "GK":1},
         "formation_shooting_rate" : [3, 3, 1.5, 1.5, 1, 1, 0.5, 0.5, 0.5, 0.5, 0],
         "formation_assist_rate" : [2, 2, 3, 3, 2, 2, 0.5, 0.5, 0.5, 1.5, 0]},
}