LEAGUE_LEVEL_DICT = {
    # 5大リーグ1部
    "Tier1":{
        "league_level":1,
        "min_starting_rate":73,
        "max_starting_rate":99,
        "min_starting_rate_mean":76,
        "max_starting_rate_mean":92,
        "min_bench_rate_mean":74,
        "max_bench_rate_mean":82,
        "mean_newplayer_rate":65,
        "category":'top', 
        "promotion_num": 0,
        "relegation_num":3,
        "age_initial_mean":27,
    },
    # 欧州5大リーグ外1部上位, 北南米1部(ポルトガル, ブラジルetc)
    "Tier2":{
        "league_level":2,
        "min_starting_rate":65,
        "max_starting_rate":82,
        "min_starting_rate_mean":69,
        "max_starting_rate_mean":78,
        "min_bench_rate_mean":66,
        "max_bench_rate_mean":74,
        "mean_newplayer_rate":64,
        "category":'top', 
        "promotion_num": 0,
        "relegation_num":3,
        "age_initial_mean":27,
    },
    # 欧州上位リーグ2部, 欧州下位リーグ1部, アジア1部,  
    "Tier3":{
        "league_level":3,
        "min_starting_rate":58,
        "max_starting_rate":76,
        "min_starting_rate_mean":62,
        "max_starting_rate_mean":73,
        "min_bench_rate_mean":60,
        "max_bench_rate_mean":69,
        "mean_newplayer_rate":63,
        "category":'top', 
        "promotion_num": 0,
        "relegation_num":3,
        "age_initial_mean":26,
    },
    "Tier4":{
        "league_level":4,
        "min_starting_rate":49,
        "max_starting_rate":70,
        "min_starting_rate_mean":53,
        "max_starting_rate_mean":67,
        "min_bench_rate_mean":51,
        "max_bench_rate_mean":63,
        "mean_newplayer_rate":62,
        "category":'top', 
        "promotion_num": 0,
        "relegation_num":3,
        "age_initial_mean":25,
    }
}